### ISSUE TITLE
Allow the use of custom hashers for FrozenMap

### ISSUE THREAD

**Issue by brendanzab** [Manishearth/elsa#13]
It would be great if `FrozenMap` let you pass a custom hasher as a type argument, for example [FNV](https://lib.rs/crates/fnvhash) or [Fx](https://lib.rs/crates/fxhash)! This is helpful for performance in compiler implementations, for example.

**Comment by Manishearth** [comment]
Happy to accept PRs!

**Comment by eddyb** [comment]
I just going to open an issue for doing what I did in #19 to more types, and found this existing one.

Anyone who wants to do this can look at #19 for inspiration.
