### ISSUE TITLE
FrozenVec invalidates references on resize

### ISSUE THREAD

**Issue by sidju** [Manishearth/elsa#29]
From what I can find .push for at least the FrozenVec risks invalidating references, as implemented at https://github.com/Manishearth/elsa/blob/master/src/vec.rs#L32 .

[https://doc.rust-lang.org/std/vec/struct.Vec.html#guarantees](https://doc.rust-lang.org/std/vec/struct.Vec.html#guarantees) describes this behaviour and when push/insert will (re)allocate.

Have I missed what you do to avoid this?

**Comment by eggyal** [comment]
> Have I missed what you do to avoid this?

Only types that implement [`StableDeref`](https://docs.rs/stable_deref_trait/1.2.0/x86_64-unknown-linux-gnu/stable_deref_trait/trait.StableDeref.html) can be inserted, so the references that are returned are not invalidated even if the owned `StableDeref` type is moved.

**Comment by sidju** [comment]
I see. Thank you for your quick response, and for the crate.
