### ISSUE TITLE
(Optional?) (Frozen)Index{Map,Set}

### ISSUE THREAD

**Issue by eddyb** [Manishearth/elsa#6]
That is, frozen versions of the the [`indexmap`](https://docs.rs/indexmap) crate (previously known as `ordermap`).
Having a guaranteed order *and* being able to use indices would come in handy, especially for interners (a `FrozenIndexSet` is pretty much *exactly* an interner).

**Comment by Manishearth** [comment]
Would accept PRs for this under a feature flag

**Comment by pczarn** [comment]
I'm currently working on this.

I'm looking for a way to avoid double lookup under a common use case of frozen index set. We are interning (`get_or_intern`) by searching with a borrowed element and converting to an owned element for insertion on lookup failure. We don't want to do double lookup for a vacant entry.

Now I need either some proof of lookup failure, or proofless insertion without lookup for existing element.

I could do a parallel to `entry` (I'd do `fn entry_by_borrowed(k: Q)`, `fn entry_by_owned(k: T)`) but it seems overly complex.

I'll think about it tomorrow.

**Comment by pczarn** [comment]
I couldn't find a simple and efficient API for interning. We would need an improved Entry API to revisit this.

See also **Extend entry API to work on borrowed keys** https://github.com/rust-lang/rfcs/pull/1769

Yet another nice-to-have thing would be a stable custom allocation story. With custom allocators, we could easily replace the meat of the `string_interner` crate. Each interner would hold its own allocator, thereby gaining top performance.

**Comment by pczarn** [comment]
Yet another possibility is adding `raw_entry` for `IndexSet` (and perhaps `IndexMap` too).

**Comment by pczarn** [comment]
cc @bluss the creator and maintainer of indexmap

**Comment by bluss** [comment]
@pczarn raw_entry should be possible in indexmap (haven't looked closely). Indexmap also supports a slightly generalized equality check (better than the Borrow mechanism), can that help?
