### ISSUE TITLE
Questions about `FrozenVec`

### ISSUE THREAD

**Issue by bzm3r** [Manishearth/elsa#64]
(This is a discussion, rather than an issue. Can it be converted into one?)

Two questions, about `FrozenVec`:

0) Am I right in understanding that `FrozenVec` will never be re-allocated on resize?

1) is `FrozenVec` more prone to fragmentation issues as it grows, since it will never be re-allocated on resize?

2) why does `FrozenVec` not expose a `with_capacity`-like for creating new `FrozenVec`s?

(Thank you! 🙏)

**Comment by Manishearth** [comment]
> * Am I right in understanding that `FrozenVec` will never be re-allocated on resize?
> *

No, it will.

> 1\. why does `FrozenVec` not expose a `with_capacity`-like for creating new `FrozenVec`s?

It could, it wasn't needed so far. Happy to merge a PR for it.
